;;;; diag-pi.lisp — diagnose delta-kvs differences
(in-package :jotl)

(defun diag-delta-kvs (trace-dir block-num)
  "Show detailed delta-kvs diffs + pre-state check."
  (let* ((step-path (trace-block-path trace-dir block-num))
         (bytes (alexandria:read-file-into-byte-vector step-path)))
    (multiple-value-bind (pre-sigma block-cl post-sigma)
        (decode-trace-step-bin bytes)
      (let ((*chain-log-level* nil))
        (declare (special *chain-log-level*))
        (let ((pre-ht (make-hash-table :test 'equalp)))
          (dolist (kv (funcall pre-sigma :merkle-kvs))
            (unless (segment-key-p (car kv))
              (setf (gethash (car kv) pre-ht) (cdr kv))))
          (multiple-value-bind (sigma-prime computed-root)
              (import-block pre-sigma block-cl)
            (declare (ignore computed-root))
            (let ((exp-ht (make-hash-table :test 'equalp))
                  (got-ht (make-hash-table :test 'equalp)))
              (dolist (kv (funcall post-sigma :merkle-kvs))
                (unless (segment-key-p (car kv))
                  (setf (gethash (car kv) exp-ht) (cdr kv))))
              (dolist (kv (funcall sigma-prime :merkle-kvs))
                (unless (segment-key-p (car kv))
                  (setf (gethash (car kv) got-ht) (cdr kv))))
              (format t "~%=== Block ~D delta-kvs diff ===~%" block-num)
              (maphash (lambda (k v)
                         (let ((got-v (gethash k got-ht))
                               (pre-v (gethash k pre-ht)))
                           (when (and got-v (not (equalp v got-v)))
                             (format t "  DIFF key=~A~%" (bytes-to-hex-string k))
                             (format t "    exp(~D)=~A~%" (length v)
                                     (subseq (bytes-to-hex-string v) 0 (min 60 (* 2 (length v)))))
                             (format t "    got(~D)=~A~%" (length got-v)
                                     (subseq (bytes-to-hex-string got-v) 0 (min 60 (* 2 (length got-v)))))
                             (if pre-v
                                 (format t "    pre(~D)=~A  got=pre? ~A~%"
                                         (length pre-v)
                                         (subseq (bytes-to-hex-string pre-v) 0 (min 60 (* 2 (length pre-v))))
                                         (equalp got-v pre-v))
                                 (format t "    pre: NOT IN PRE-STATE~%")))))
                       exp-ht))))))))

(defun diag-delta-kvs-range (trace-dir blocks)
  (dolist (b blocks)
    (handler-case
        (diag-delta-kvs trace-dir b)
      (error (e) (format t "Block ~D: ERROR ~A~%" b e)))))

;;; ═══════════════════════════════════════════════════════════════
;;; Trace storage writes with h27 and value
;;; ═══════════════════════════════════════════════════════════════

(defun diag-storage-rw (trace-dir block-num target-sid)
  "Intercept storage reads and writes for TARGET-SID."
  (let* ((step-path (trace-block-path trace-dir block-num))
         (bytes (alexandria:read-file-into-byte-vector step-path))
         (*chain-log-level* nil)
         (jotl::*debug-pvm-trace* t)
         (jotl::*debug-pvm-traces* nil)
         (rw-log nil))
    (declare (special *chain-log-level* jotl::*debug-pvm-trace* jotl::*debug-pvm-traces*))
    (let ((orig-write (gethash 4 jam-host::*omega-table*))
          (orig-read  (gethash 3 jam-host::*omega-table*)))
      ;; Hook writes
      (setf (gethash 4 jam-host::*omega-table*)
            (lambda (vm ctx)
              (let* ((key-ptr   (jamvm:u32 (jamvm:reg vm jamvm:+a0+)))
                     (key-len   (jamvm:u32 (jamvm:reg vm jamvm:+a1+)))
                     (value-ptr (jamvm:u32 (jamvm:reg vm jamvm:+a2+)))
                     (value-len (jamvm:u32 (jamvm:reg vm jamvm:+a3+)))
                     (key (jam-host:read-guest vm key-ptr key-len))
                     (value (when (plusp value-len)
                              (jam-host:read-guest vm value-ptr value-len)))
                     (h27 (when key (jam-host:storage-hash-key key))))
                (when (and key (= (jam-host::hctx-service-id ctx) target-sid))
                  (push (list :op :WRITE :h27 h27 :key-len key-len :val-len value-len
                              :val-hex (when value (bytes-to-hex-string value))
                              :pc (jamvm:pvm-pc vm) :gas (jamvm:pvm-gas vm))
                        rw-log)))
              (funcall orig-write vm ctx)))
      ;; Hook reads (self-storage only)
      (setf (gethash 3 jam-host::*omega-table*)
            (lambda (vm ctx)
              (let* ((service-raw (jamvm:reg vm jamvm:+a0+))
                     (key-ptr     (jamvm:u32 (jamvm:reg vm jamvm:+a1+)))
                     (key-len     (jamvm:u32 (jamvm:reg vm jamvm:+a2+)))
                     (is-self (or (= service-raw jam-host::+hc-none+)
                                  (= service-raw (jamvm:u64 (jam-host::hctx-service-id ctx))))))
                (when (and is-self (= (jam-host::hctx-service-id ctx) target-sid))
                  (let* ((key (jam-host:read-guest vm key-ptr key-len))
                         (h27 (when key (jam-host:storage-hash-key key)))
                         (cur-val (when h27 (gethash h27 (jam-host::hctx-storage ctx)))))
                    (push (list :op :READ :h27 h27 :key-len key-len
                                :cur-val (when cur-val (bytes-to-hex-string cur-val))
                                :cur-len (when cur-val (length cur-val))
                                :pc (jamvm:pvm-pc vm) :gas (jamvm:pvm-gas vm))
                          rw-log))))
              (funcall orig-read vm ctx)))
      (unwind-protect
          (progn
            (multiple-value-bind (pre-sigma block-cl post-sigma)
                (decode-trace-step-bin bytes)
              (declare (ignore post-sigma))
              (import-block pre-sigma block-cl))
            (format t "~%=== Block ~D SID=~D storage R/W trace ===~%" block-num target-sid)
            (dolist (entry (nreverse rw-log))
              (let ((op (getf entry :op))
                    (h27 (getf entry :h27))
                    (pc (getf entry :pc))
                    (gas (getf entry :gas)))
                (if (eq op :READ)
                    (format t "  [pc=~D gas=~D] READ  h27=~A cur=~A~%"
                            pc gas
                            (subseq (bytes-to-hex-string h27) 0 12)
                            (or (getf entry :cur-val) "NONE"))
                    (format t "  [pc=~D gas=~D] WRITE h27=~A val(~D)=~A~%"
                            pc gas
                            (subseq (bytes-to-hex-string h27) 0 12)
                            (getf entry :val-len)
                            (or (getf entry :val-hex) "DELETE"))))))
        ;; Restore
        (setf (gethash 4 jam-host::*omega-table*) orig-write)
        (setf (gethash 3 jam-host::*omega-table*) orig-read)))))
