#!/usr/bin/env python3
"""
Verify JAM test vectors against Gray Paper §6.1-6.2
Generated by JOTL (JAM On The Lisp)
"""

import json
import sys
from pathlib import Path

C11_KEY = '0x0b000000000000000000000000000000000000000000000000000000000000'

def decode_u32_le(hex_str):
    """Decode u32 little-endian from hex string"""
    val_bytes = bytes.fromhex(hex_str[2:])
    return int.from_bytes(val_bytes[:4], 'little')

def find_state_value(keyvals, key):
    """Find value for key in state keyvals"""
    for kv in keyvals:
        if kv['key'] == key:
            return kv['value']
    return None

def verify_trace(trace_file):
    """Verify a single trace file"""
    with open(trace_file) as f:
        data = json.load(f)
    
    # Extract values
    HT = data['block']['header']['slot']
    
    tau_hex = find_state_value(data['pre_state']['keyvals'], C11_KEY)
    tau_prime_hex = find_state_value(data['post_state']['keyvals'], C11_KEY)
    
    if not tau_hex or not tau_prime_hex:
        print(f"  ⚠ C11 key not found in {trace_file.name}")
        return False
    
    tau = decode_u32_le(tau_hex)
    tau_prime = decode_u32_le(tau_prime_hex)
    
    # Calculate epochs (E=12 for tiny chain)
    E = 12
    e, m = divmod(tau, E)
    e_prime, m_prime = divmod(tau_prime, E)
    
    # Verify Gray Paper §6.1
    valid = (tau_prime == HT)
    
    print(f"  File: {trace_file.name}")
    print(f"    PRE:  τ={tau:3d}  (epoch {e}, phase {m:2d})")
    print(f"    HEAD: HT={HT:3d}")
    print(f"    POST: τ'={tau_prime:3d} (epoch {e_prime}, phase {m_prime:2d})")
    print(f"    {'✅ VALID' if valid else '❌ INVALID'}: τ' == HT ? {tau_prime} == {HT}")
    
    # Check for epoch transition
    if e_prime > e:
        print(f"    🔄 NEW EPOCH: {e} → {e_prime}")
    
    print()
    return valid

def main():
    traces_dir = Path(__file__).parent.parent / 'test' / 'jamtestvectors' / 'traces' / 'fallback'
    
    if not traces_dir.exists():
        print(f"Error: {traces_dir} not found")
        return 1
    
    print("═" * 60)
    print("JAM TEST VECTOR VERIFICATION - Gray Paper §6.1-6.2")
    print("═" * 60)
    print()
    
    # Get all JSON trace files (skip genesis for now)
    json_files = sorted([f for f in traces_dir.glob('*.json') 
                        if f.name != 'genesis.json'])
    
    # Verify first 20 traces
    valid_count = 0
    num_to_test = min(20, len(json_files))
    
    for trace_file in json_files[:num_to_test]:
        if verify_trace(trace_file):
            valid_count += 1
    
    print("═" * 60)
    print(f"Results: {valid_count}/{num_to_test} traces valid")
    if valid_count == num_to_test:
        print("✅ ALL TESTS PASSED - Implementation matches Gray Paper §6.1!")
    else:
        print("❌ SOME TESTS FAILED - Check implementation")
    print("═" * 60)
    
    return 0 if valid_count == num_to_test else 1

if __name__ == '__main__':
    sys.exit(main())
