;;;; bloc/block.lisp — JAM Block B ≡ (H, E)
;;;; Gray Paper §4.1-4.2
;;;;
;;;; Messages:
;;;;   :header, :extrinsic               — direct fields
;;;;   :tickets, :disputes, :preimages,  — extrinsic passthrough
;;;;   :assurances, :guarantees
;;;;   :slot, :timeslot, :parent-hash,   — header passthrough
;;;;   :state-root
;;;;   :hash              — H(E(H))
;;;;   :encoded           — E(B) = E(H) || E(E)
;;;;   :is-genesis        — genesis check
;;;;   :decode bytes off  — (values B-closure consumed)

(in-package #:jotl)

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK CLOSURE — define-state-closure
;;; ═════════════════════════════════════════════════════════════════
;;;
;;; Tout passe par messages — pas de defun encode standalone.

(define-state-closure block
  ((header nil) (extrinsic nil))

  ;; ── Extrinsic passthrough ────────────────────────────────────
  (:tickets    (funcall extrinsic :tickets))
  (:disputes   (funcall extrinsic :disputes))
  (:preimages  (funcall extrinsic :preimages))
  (:assurances (funcall extrinsic :assurances))
  (:guarantees (funcall extrinsic :guarantees))

  ;; ── Header passthrough ──────────────────────────────────────
  (:slot        (funcall header :slot))
  (:timeslot    (funcall header :slot))
  (:parent-hash (funcall header :parent-hash))
  (:state-root  (funcall header :state-root))

  ;; ── Memoized ─────────────────────────────────────────────────
  (:hash :memo (funcall header :hash))
  (:encoded :memo
   (concatenate '(vector (unsigned-byte 8))
                (funcall header :encoded)
                (funcall extrinsic :encoded)))

  ;; ── Convenience ──────────────────────────────────────────────
  (:is-genesis (funcall header :is-genesis))

  ;; ── Decode: bytes → B closure ───────────────────────────────
  ;; Delegates to H :decode then E :decode, wraps in B
  (:decode (bytes offset)
    (let ((pos (or offset 0)))
      (multiple-value-bind (h h-consumed)
          (funcall (make-header) :decode bytes pos)
        (incf pos h-consumed)
        (multiple-value-bind (e e-consumed)
            (funcall (make-extrinsic) :decode bytes pos)
          (incf pos e-consumed)
          (values (make-block :header h :extrinsic e)
                  (- pos (or offset 0))))))))

;;; decode-block is auto-generated by define-state-closure:
;;;   (decode-block bytes offset) → (values B-closure consumed)
