;;;; bloc/block.lisp — JAM Block B ≡ (H, ET, ED, EP, EA, EG)
;;;; Gray Paper §4.1-4.2
;;;;
;;;; The block is a MESSAGE, not an actor.  In Kay's model:
;;;;   σ is the actor  (state closure with identity, state, transitions)
;;;;   B is the message sent to σ
;;;;   Υ is the handler for that message
;;;;
;;;; Header (H) stays a closure — genuine sovereignty (hash, EU(H), genesis).
;;;; Extrinsic sub-elements are raw data — consumed directly by state closures.
;;;;
;;;; Messages:
;;;;   :header                             — H closure
;;;;   :tickets, :disputes, :preimages,    — raw extrinsic data (auto-generated)
;;;;   :assurances, :guarantees
;;;;   :reports                            — alias for guarantees
;;;;   :extrinsic-hash                     — HX (memoized)
;;;;   :hash                               — H(E(H)) (memoized)
;;;;   :encoded                            — E(B) = E(H) || E(E) (memoized)
;;;;   :is-genesis                         — genesis check
;;;;   :decode bytes off                   — (values B-closure consumed)

(in-package #:jotl)

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK CLOSURE — B = (H, ET, ED, EP, EA, EG)
;;; ═════════════════════════════════════════════════════════════════
;;;
;;; H is a closure (sovereignty over hash/encode/genesis).
;;; ET, ED, EP, EA, EG are raw data — open for consumption.
;;; Field accessors (:tickets, :disputes, etc.) are auto-generated
;;; by define-state-closure — no passthrough needed.

(define-state-closure block
  ((header nil)
   (tickets nil) (disputes nil) (preimages nil)
   (assurances nil) (guarantees nil))

  ;; ── GP alias ───────────────────────────────────────────────────
  (:reports guarantees)

  ;; ── HX — absorbed from extrinsic (§5.4-5.6) ──────────────────
  (:extrinsic-hash :memo
    (compute-extrinsic-hash tickets disputes preimages assurances guarantees))

  ;; ── E(B) = E(H) || E(E) ───────────────────────────────────────
  (:encoded :memo
   (concatenate '(vector (unsigned-byte 8))
                (funcall header :encoded)
                (encode-extrinsic-data tickets disputes preimages
                                       assurances guarantees)))

  ;; ── Hash H(E(H)) ──────────────────────────────────────────────
  (:hash :memo (funcall header :hash))

  ;; ── Convenience ────────────────────────────────────────────────
  (:is-genesis (funcall header :is-genesis))

  ;; ── Decode: bytes → B closure ─────────────────────────────────
  ;; Decodes H (closure) then extrinsic data (raw parts).
  (:decode (bytes offset)
    (let ((pos (or offset 0)))
      (multiple-value-bind (h h-consumed)
          (funcall (make-header) :decode bytes pos)
        (incf pos h-consumed)
        (multiple-value-bind (et ed ep ea eg e-consumed)
            (decode-extrinsic-data bytes pos)
          (incf pos e-consumed)
          (values (make-block :header h
                              :tickets et :disputes ed :preimages ep
                              :assurances ea :guarantees eg)
                  (- pos (or offset 0))))))))

;;; decode-block is auto-generated by define-state-closure:
;;;   (decode-block bytes offset) → (values B-closure consumed)
