;;;; stf/sigma.lisp — JAM State σ (Pure FP)
;;;; Gray Paper §4.2 & §4.4
;;;;
;;;; σ = (α, β, θ, γ, δ, η, ι, κ, λ, ρ, τ, ϕ, χ, ψ, π, ω, ξ)
;;;;
;;;; DATA — immutable state closure.
;;;; Transitions produce σ' (see stf/upsilon.lisp).

(in-package #:jotl)

;;; ===================================================================
;;; GRAY PAPER §4.4: THE STATE
;;; ===================================================================
;;;
;;; σ = (α, β, θ, γ, δ, η, ι, κ, λ, ρ, τ, ϕ, χ, ψ, π, ω, ξ)
;;;
;;; Segments:
;;;   α  alpha  - Core authorizations
;;;   β  beta   - Recent block headers
;;;   θ  theta  - Accumulation queue
;;;   γ  gamma  - Safrole state (tickets, entropy, validator selection)
;;;   δ  delta  - Services
;;;   η  eta    - Entropy pool
;;;   ι  iota   - Enqueued validator keys (next epoch)
;;;   κ  kappa  - Current validator keys
;;;   λ  lambda - Archived validator keys (prior epoch)
;;;   ρ  rho    - Core assignments (reports pending availability)
;;;   τ  tau    - Timeslot index
;;;   ϕ  phi    - Authorization queue
;;;   χ  chi    - Privileged service IDs
;;;   ψ  psi    - Judgments
;;;   π  pi     - Validator activity statistics
;;;   ω  omega  - Ready work-reports
;;;   ξ  xi     - Recently accumulated work-packages

;;; ===================================================================
;;; STATE CLOSURE — generated by define-value-object
;;; ===================================================================
;;; lambda* and pi* use trailing * to avoid CL reserved names.
;;; The macro strips * for message keys: :lambda, :pi.

(define-value-object state
  ((alpha nil)
   (beta nil)
   (theta nil)
   (gamma nil)
   (delta nil)
   (eta nil)
   (iota nil)
   (kappa nil)
   (lambda* nil)
   (rho nil)
   (tau 0)
   (phi nil)
   (chi nil)
   (psi nil)
   (pi* nil)
   (omega nil)
   (xi nil))
  ;; Derived messages
      (:epoch (timeslot-epoch tau))
      (:phase (timeslot-phase tau))
  (:epoch-and-phase (timeslot-to-epoch-and-phase tau)))

;;; ===================================================================
;;; GENESIS STATE σ₀
;;; ===================================================================

(defun make-genesis-state (&key validators)
  "Creates genesis state σ₀.
   
   Gray Paper: We presume consensus over H₀ and σ₀."
  (make-state
   :tau 0
   :kappa validators
   :beta nil
   :eta (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)))
