;;;; block/block.lisp — JAM Block B ≡ (H, E)
;;;; Gray Paper §4.1-4.2
;;;;
;;;; Single source of truth: closure + encode/decode + hash.
;;;; decode-block returns closures — ONE representation everywhere.

(in-package #:jotl)

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK CLOSURE — via define-value-object
;;; ═════════════════════════════════════════════════════════════════
;;;
;;; GP §4.2: B ≡ (H, E)
;;;
;;; Fields → :header, :extrinsic
;;; Passthrough → extrinsic and header sub-messages
;;; Memoized → :encoded (computed once)

(define-value-object block
  ((header nil) (extrinsic nil))
  ;; Extrinsic passthrough
  (:tickets    (funcall extrinsic :tickets))
  (:disputes   (funcall extrinsic :disputes))
  (:preimages  (funcall extrinsic :preimages))
  (:assurances (funcall extrinsic :assurances))
  (:guarantees (funcall extrinsic :guarantees))
  ;; Header passthrough
  (:slot       (funcall header :slot))
  (:timeslot   (funcall header :slot))
  (:parent-hash (funcall header :parent-hash))
  (:state-root (funcall header :state-root))
  ;; Hash (block hash = header hash)
  (:hash       (funcall header :hash))
  ;; Memoized encoding
  (:encoded :memo
   (concatenate '(vector (unsigned-byte 8))
                (funcall header :encoded)
                (funcall extrinsic :encoded)))
  ;; Convenience
  (:is-genesis (funcall header :is-genesis)))

;;; Non-field accessors (passthrough, not generated by macro)

(defun block-tickets (b) "ET" (funcall b :tickets))
(defun block-disputes (b) "ED" (funcall b :disputes))
(defun block-preimages (b) "EP" (funcall b :preimages))
(defun block-assurances (b) "EA" (funcall b :assurances))
(defun block-guarantees (b) "EG" (funcall b :guarantees))
(defun block-slot (b) "HT" (funcall b :slot))

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK ENCODING
;;; ═════════════════════════════════════════════════════════════════

(defun encode-block (header extrinsic)
  "Encode block B ≡ (H, E). Accepts closures."
  (concatenate '(vector (unsigned-byte 8))
               (funcall header :encoded)
               (funcall extrinsic :encoded)))

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK DECODING — returns closures
;;; ═════════════════════════════════════════════════════════════════

(defun decode-block (bytes &optional (offset 0))
  "Decode block B ≡ (H, E) from binary.
   
   Returns CLOSURES — not plists. This is the single entry point.
   
   Returns: (values block-closure total-bytes-consumed)"
  (let ((pos offset))
    ;; 1. Decode header → plist
    (multiple-value-bind (h-plist header-bytes)
        (decode-header bytes pos)
      (incf pos header-bytes)
      ;; 2. Decode extrinsic → plist
      (multiple-value-bind (e-plist extrinsic-bytes)
          (decode-extrinsic bytes pos)
        (incf pos extrinsic-bytes)
        ;; 3. Wrap in closures
        (let* ((header (apply #'make-header h-plist))
               (extrinsic (make-extrinsic
                           :tickets    (getf e-plist :tickets)
                           :disputes   (getf e-plist :disputes)
                           :preimages  (getf e-plist :preimages)
                           :assurances (getf e-plist :assurances)
                           :guarantees (getf e-plist :guarantees)))
               (block (make-block :header header :extrinsic extrinsic)))
          (values block (- pos offset)))))))

;;; ═════════════════════════════════════════════════════════════════
;;; BLOCK HASHING
;;; ═════════════════════════════════════════════════════════════════

(defun compute-block-hash (block)
  "Block hash = header hash H(E(H))."
  (funcall (funcall block :header) :hash))

;;; ═════════════════════════════════════════════════════════════════
;;; HELPERS
;;; ═════════════════════════════════════════════════════════════════

(defun validate-block-structure (block)
  "Basic structural check: header and extrinsic present."
  (assert (funcall block :header) () "Block must have a header")
  (assert (funcall block :extrinsic) () "Block must have an extrinsic")
  t)

(defun block-size (block)
  "Size of encoded block in bytes."
  (length (funcall block :encoded)))

;;; Exports managed in package.lisp
