;;;; state/sigma.lisp — σ Overall State (GP §4.1, §4.4)
;;;;
;;;; σ = (α, β, γ, δ, η, ι, κ, λ, ρ, τ, ϕ, χ, ψ, π, ω, ξ, θ)
;;;;
;;;; σ is a PURE BYTE STORE — fields are raw encoded bytes, not closures.
;;;; Υ(σ, B) → σ' lives in upsilon.lisp.
;;;;
;;;; σ OWNS the Merkle mapping AND the decode dispatch:
;;;;   - σ knows WHERE each component sits in the Merkle trie: C(n).
;;;;   - σ knows HOW to decode each component (dispatches to decode-NAME).
;;;;   - Components know their codec; σ knows where they live.
;;;;
;;;; Lazy decoding protocol:
;;;;   1. σ stores raw byte vectors for each component.
;;;;   2. Upsilon loads on demand:
;;;;        (funcall sigma :load :tau) → τ closure
;;;;      σ fetches its bytes, calls the component's decoder, returns the closure.
;;;;   3. After transitions, closures are re-encoded:
;;;;        (make-sigma-state :tau (funcall tau-prime :encoded) ...)
;;;;
;;;; Encoding flow (σ → Merkle):
;;;;   σ pairs C(n) + raw bytes for each non-nil field → Merkle KV
;;;;   No funcall :encoded needed — it's already bytes.
;;;;
;;;; Messages:
;;;;   :segment kw          → raw bytes for keyword (e.g. :tau), or NIL
;;;;   :load kw             → decoded closure for keyword (lazy decode from bytes)
;;;;   :merkle-kvs          → list of (C(n) . bytes) for the Merkle trie
;;;;   :state-root          → H(trie(:merkle-kvs))
;;;;   :state-key-for kw    → C(n) for a component keyword
;;;;   :components          → list of non-nil segment keywords

(in-package #:jotl)

;;; ═══════════════════════════════════════════════════════════════
;;; SEGMENT ORDER — C(1)..C(16) mapping  (GP Appendix D)
;;; ═══════════════════════════════════════════════════════════════

(defparameter +sigma-segment-order+
  '((:alpha  . 1)  (:phi    . 2)  (:beta   . 3)  (:gamma  . 4)
    (:psi    . 5)  (:eta    . 6)  (:iota   . 7)  (:kappa  . 8)
    (:lambda . 9)  (:rho    . 10) (:tau    . 11) (:chi    . 12)
    (:pi     . 13) (:omega  . 14) (:xi     . 15) (:theta  . 16))
  "Maps segment keyword → C(n) index.  δ uses C(255,s) and is separate.")

;;; ═══════════════════════════════════════════════════════════════
;;; DECODE DISPATCH — σ knows which decoder to call per keyword
;;; ═══════════════════════════════════════════════════════════════
;;; Each decode-NAME function is generated by define-state-closure
;;; and takes (bytes offset) → (values closure consumed).
;;; σ is loaded last, so all decoders are available.

(defun sigma-decode-segment (kw bytes)
  "Dispatch decode for segment keyword KW on raw BYTES.
   Returns the decoded closure, or signals error for unknown KW."
  (ecase kw
    (:tau    (decode-tau-state bytes 0))
    (:eta    (decode-eta-state bytes 0))
    (:kappa  (decode-kappa-state bytes 0))
    (:lambda (decode-lambda-state bytes 0))
    (:iota   (decode-iota-state bytes 0))
    (:beta   (decode-beta-state bytes 0))
    (:psi    (decode-psi-state bytes 0))
    (:rho    (decode-rho-state bytes 0))
    (:gamma  (decode-gamma-state bytes 0))
    (:pi     (decode-pi-state bytes 0))
    ;; Placeholders — will be added as components get implemented:
    ;; (:alpha  (decode-alpha-state bytes 0))
    ;; (:phi    (decode-phi-state bytes 0))
    ;; (:delta  (decode-delta-state bytes 0))
    ;; (:chi    (decode-chi-state bytes 0))
    ;; (:omega  (decode-omega-state bytes 0))
    ;; (:xi     (decode-xi-state bytes 0))
    ;; (:theta  (decode-theta-state bytes 0))
    ))

;;; ═══════════════════════════════════════════════════════════════
;;; STATE CLOSURE — σ (byte store)
;;; ═══════════════════════════════════════════════════════════════
;;; All fields are raw byte vectors (or NIL for unimplemented components).
;;; No closures are stored — sigma is inert data.

(define-state-closure sigma-state
  ;; ── 17 component byte fields ──
  ;; Each is (simple-array (unsigned-byte 8) (*)) or NIL.
  ((alpha nil) (beta nil) (gamma nil) (delta nil)
   (eta nil) (iota nil) (kappa nil) (lambda* nil)
   (rho nil) (tau nil) (phi nil) (chi nil)
   (psi nil) (pi* nil) (omega nil) (xi nil) (theta nil))

  ;; ── Segment access — raw bytes ─────────────────────────────
  ;; (funcall sigma :segment :tau) → raw bytes or NIL
  (:segment (component-kw)
    (case component-kw
      (:alpha   alpha)
      (:beta    beta)
      (:gamma   gamma)
      (:delta   delta)
      (:eta     eta)
      (:iota    iota)
      (:kappa   kappa)
      (:lambda  lambda*)
      (:rho     rho)
      (:tau     tau)
      (:phi     phi)
      (:chi     chi)
      (:psi     psi)
      (:pi      pi*)
      (:omega   omega)
      (:xi      xi)
      (:theta   theta)
      (otherwise nil)))

  ;; ── Load — lazy decode from bytes ───────────────────────────
  ;; (funcall sigma :load :tau) → τ closure (or NIL if no bytes)
  ;; σ fetches its bytes, dispatches to the right decoder, returns closure.
  ;; NOTE: :load, not :decode — :decode is reserved for codec in the macro.
  (:load (component-kw)
    (let ((bytes (self :segment component-kw)))
      (when bytes
        (sigma-decode-segment component-kw bytes))))

  ;; ── Merkle KV pairs (memoized) ──────────────────────────────
  ;; σ already has bytes — just pair each non-nil field with C(n).
  ;; GP Appendix D — 16 fixed segments + service accounts.
  (:merkle-kvs :memo
    (let ((kvs '()))
      (dolist (entry +sigma-segment-order+)
        (let* ((kw (car entry))
               (cn-idx (cdr entry))
               (bytes (self :segment kw)))
          (when bytes
            (push (cons (state-key cn-idx) bytes) kvs))))
      ;; Service accounts — δ uses C(255, s) keys
      ;; TODO: when δ is implemented, append its Merkle KVs
      (nreverse kvs)))

  ;; ── State root (memoized) ──────────────────────────────────
  ;; HR = H(trie(merkle-kvs))   GP §D
  (:state-root :memo
    (compute-state-root (self :merkle-kvs)))

  ;; ── State key for a component keyword ──────────────────────
  ;; (funcall sigma :state-key-for :tau) → C(11)
  (:state-key-for (component-kw)
    (let ((entry (assoc component-kw +sigma-segment-order+)))
      (when entry
        (state-key (cdr entry)))))

  ;; ── Active components (non-nil segment keywords) ───────────
  (:components
    (loop for (kw . _n) in +sigma-segment-order+
          when (self :segment kw) collect kw)))


;;; ═══════════════════════════════════════════════════════════════
;;; CONVENIENCE — merklize & validate (forwarding to σ messages)
;;; ═══════════════════════════════════════════════════════════════

(defun merklize-state (sigma)
  "GP §D — Compute state root HR = Merkle root of σ.
   Delegates to σ's :state-root message."
  (funcall sigma :state-root))

(defun validate-state-root (header sigma-prime)
  "GP §5 — Validate HR = Merkle root of σ'.
   Signals error on mismatch."
  (let ((expected-hr (funcall sigma-prime :state-root))
        (actual-hr   (funcall header :state-root)))
    (unless (equalp actual-hr expected-hr)
      (error "HR mismatch: state root does not match Merkle root of σ'"))
    t))

;;; ═══════════════════════════════════════════════════════════════
;;; GENESIS STATE — σ₀
;;; ═══════════════════════════════════════════════════════════════

(defun make-genesis-state ()
  "σ₀ — Genesis state: all implemented components at default encoded bytes.
   Every component that transition-state expects MUST be present here.
   Components still at placeholder stage (nil) will be populated as
   they get implemented."
  (make-sigma-state
   :tau    (funcall (make-tau-state) :encoded)
   :eta    (funcall (make-eta-state) :encoded)
   :kappa  (funcall (make-kappa-state) :encoded)
   :lambda* (funcall (make-lambda-state) :encoded)
   :iota   (funcall (make-iota-state) :encoded)
   :beta   (funcall (make-beta-state) :encoded)
   :psi    (funcall (make-psi-state) :encoded)
   :rho    (funcall (make-rho-state) :encoded)
   :gamma  (funcall (make-gamma-state) :encoded)
   :pi*    (funcall (make-pi-state) :encoded)
   ;; ── Placeholders — populated when implemented ──
   ;; :alpha  nil   ;; TODO: make-alpha-state
   ;; :delta  nil   ;; TODO: make-delta-state
   ;; :phi    nil   ;; TODO: make-phi-state
   ;; :chi    nil   ;; TODO: make-chi-state
   ;; :omega  nil   ;; TODO: make-omega-state
   ;; :xi     nil   ;; TODO: make-xi-state
   ;; :theta  nil   ;; TODO: make-theta-state
   ))
