;;;; state/sigma.lisp — σ Overall State (GP §4.1, §4.4)
;;;;
;;;; σ = (α, β, γ, δ, η, ι, κ, λ, ρ, τ, ϕ, χ, ψ, π, ω, ξ, θ)
;;;;
;;;; σ is a PURE BYTE STORE — fields are raw encoded bytes, not closures.
;;;; Υ(σ, B) → σ' is σ's own :transition message (delegates to transition-state
;;;; in upsilon.lisp, which implements the wave-ordered dependency graph).
;;;;
;;;; σ OWNS the Merkle mapping, the decode dispatch, AND its transition:
;;;;   - σ knows WHERE each component sits in the Merkle trie: C(n).
;;;;   - σ knows HOW to load each component (dispatches to load-NAME).
;;;;   - σ transforms itself via :transition (like every other closure).
;;;;   - Components know their codec; σ knows where they live.
;;;;
;;;; Lazy decoding protocol:
;;;;   1. σ stores raw byte vectors for each component.
;;;;   2. The transition loads on demand:
;;;;        (funcall sigma :load :tau) → τ closure
;;;;      σ fetches its bytes, calls the component's decoder, returns the closure.
;;;;   3. After transitions, closures are re-encoded:
;;;;        (make-sigma-state :tau (funcall tau-prime :save) ...)
;;;;
;;;; Encoding flow (σ → Merkle):
;;;;   σ pairs C(n) + raw bytes for each non-nil field → Merkle KV
;;;;   No funcall :save needed — it's already bytes.
;;;;
;;;; Loading from keyvals (genesis.bin, trace pre/post states):
;;;;   load-state-from-keyvals maps 31-byte Merkle keys → segment fields
;;;;   + collects non-segment keys (service accounts) into extra-kvs.
;;;;
;;;; Messages:
;;;;   :segment kw          → raw bytes for keyword (e.g. :tau), or NIL
;;;;   :load kw             → decoded closure for keyword (lazy decode from bytes)
;;;;   :merkle-kvs          → list of (C(n) . bytes) for the Merkle trie
;;;;   :state-root          → H(trie(:merkle-kvs))
;;;;   :extra-kvs           → non-segment Merkle entries (service accounts)
;;;;   :components          → list of non-nil segment keywords
;;;;   :transition (&key block) → σ' (delegates to transition-state in upsilon.lisp)

(in-package #:jotl)

;;; ═══════════════════════════════════════════════════════════════
;;; SEGMENT ORDER — C(1)..C(16) mapping  (GP Appendix D)
;;; ═══════════════════════════════════════════════════════════════

(defparameter +sigma-segment-order+
  '((:alpha  . 1)  (:phi    . 2)  (:beta   . 3)  (:gamma  . 4)
    (:psi    . 5)  (:eta    . 6)  (:iota   . 7)  (:kappa  . 8)
    (:lambda . 9)  (:rho    . 10) (:tau    . 11) (:chi    . 12)
    (:pi     . 13) (:omega  . 14) (:xi     . 15) (:theta  . 16))
  "Maps segment keyword → C(n) index.  δ uses C(255,s) and is separate.")

;;; ═══════════════════════════════════════════════════════════════
;;; LOAD DISPATCH — σ knows which loader to call per keyword
;;; ═══════════════════════════════════════════════════════════════
;;; Each load-NAME function is generated by define-state-closure
;;; and takes (bytes offset) → (values closure consumed).
;;; σ is loaded last, so all loaders are available.

(defun sigma-decode-segment (kw bytes)
  "Dispatch load for segment keyword KW on raw BYTES.
   Returns the loaded closure, or signals error for unknown KW."
  (ecase kw
    (:tau    (load-tau-state bytes 0))
    (:eta    (load-eta-state bytes 0))
    (:kappa  (load-kappa-state bytes 0))
    (:lambda (load-lambda-state bytes 0))
    (:iota   (load-iota-state bytes 0))
    (:beta   (load-beta-state bytes 0))
    (:psi    (load-psi-state bytes 0))
    (:rho    (load-rho-state bytes 0))
    (:gamma  (load-gamma-state bytes 0))
    (:pi     (load-pi-state bytes 0))
    ;; Codec-only closures (no :transition — modified by accumulate.lisp):
    (:alpha  (load-alpha-state bytes 0))
    (:phi    (load-phi-state bytes 0))
    (:chi    (load-chi-state bytes 0))
    (:omega  (load-omega-state bytes 0))
    (:xi     (load-xi-state bytes 0))
    (:theta  (load-theta-state bytes 0))
    ;; δ uses C(255,s) extra-kvs, not a fixed segment — see load-delta-from-extra-kvs.
    ))

;;; ═══════════════════════════════════════════════════════════════
;;; STATE CLOSURE — σ (byte store)
;;; ═══════════════════════════════════════════════════════════════
;;; All fields are raw byte vectors (or NIL for unimplemented components).
;;; No closures are stored — sigma is inert data.
;;;
;;; extra-kvs holds non-segment Merkle entries (service accounts C(255,s),
;;; or any future non-fixed-segment keys).  Each entry is (key-31b . bytes).

(define-state-closure sigma-state
  ;; ── 17 component byte fields ──
  ;; Each is (simple-array (unsigned-byte 8) (*)) or NIL.
  ((alpha nil) (beta nil) (gamma nil) (delta nil)
   (eta nil) (iota nil) (kappa nil) (lambda* nil)
   (rho nil) (tau nil) (phi nil) (chi nil)
   (psi nil) (pi* nil) (omega nil) (xi nil) (theta nil)
   ;; ── Non-segment Merkle entries (service accounts etc.) ──
   (extra-kvs nil))

  ;; ── Segment access — raw bytes ─────────────────────────────
  ;; (funcall sigma :segment :tau) → raw bytes or NIL
  (:segment (component-kw)
    (case component-kw
      (:alpha   alpha)
      (:beta    beta)
      (:gamma   gamma)
      (:delta   delta)
      (:eta     eta)
      (:iota    iota)
      (:kappa   kappa)
      (:lambda  lambda*)
      (:rho     rho)
      (:tau     tau)
      (:phi     phi)
      (:chi     chi)
      (:psi     psi)
      (:pi      pi*)
      (:omega   omega)
      (:xi      xi)
      (:theta   theta)
      (otherwise nil)))

  ;; ── Load — lazy decode from bytes ───────────────────────────
  ;; (funcall sigma :load :tau) → τ closure (or NIL if no bytes)
  ;; σ fetches its bytes, dispatches to the right decoder, returns closure.
  ;; σ fetches raw bytes and dispatches to the right load-NAME loader.
  (:load (component-kw)
    (let ((bytes (self :segment component-kw)))
      (when bytes
        (sigma-decode-segment component-kw bytes))))

  ;; ── Merkle KV pairs (memoized) ──────────────────────────────
  ;; σ already has bytes — just pair each non-nil field with C(n).
  ;; GP Appendix D — 16 fixed segments + service accounts.
  ;; Keys are 31-byte (compute-state-root will pad to 32).
  (:merkle-kvs :memo
    (let ((kvs '()))
      ;; C(1)..C(16) — fixed segments
      (dolist (entry +sigma-segment-order+)
        (let* ((kw (car entry))
               (cn-idx (cdr entry))
               (bytes (self :segment kw)))
          (when bytes
            ;; Build 31-byte key: [n, 0, 0, ..., 0]
            (let ((key (make-array 31 :element-type '(unsigned-byte 8)
                                      :initial-element 0)))
              (setf (aref key 0) cn-idx)
              (push (cons key bytes) kvs)))))
      ;; Non-segment entries (service accounts C(255,s), etc.)
      (dolist (kv extra-kvs)
        (push kv kvs))
      (nreverse kvs)))

  ;; ── State root (memoized) ──────────────────────────────────
  ;; HR = H(trie(merkle-kvs))   GP §D
  (:state-root :memo
    (compute-state-root (self :merkle-kvs)))

  ;; extra-kvs is a field → message :extra-kvs auto-generated by macro

  ;; ── Active components (non-nil segment keywords) ───────────
  (:components
    (loop for (kw . _n) in +sigma-segment-order+
          when (self :segment kw) collect kw))

  ;; ── Transition: Υ(σ, B) → σ' ──────────────────────────────
  ;; σ transforms itself by delegating to transition-state (upsilon.lisp).
  ;; This completes the symmetry: every closure answers :transition.
  (:transition (&key block)
    (transition-state #'self block)))


;;; ═══════════════════════════════════════════════════════════════
;;; LOAD STATE FROM KEYVALS — the universal σ constructor
;;; ═══════════════════════════════════════════════════════════════
;;; Used by genesis loader, trace loader, and any future state source.
;;; Input: list of (31-byte-key . raw-bytes) pairs from Merkle trie.
;;; Output: σ closure with all segments populated.

(defun segment-key-p (key-31)
  "Is KEY-31 a fixed segment key C(n) (first byte 1-16, rest zero)?"
  (and (>= (length key-31) 1)
       (<= 1 (aref key-31 0) 16)
       (loop for i from 1 below (length key-31) always (zerop (aref key-31 i)))))

(defun load-state-from-keyvals (keyvals)
  "Build σ from a list of (31-byte-key . raw-bytes) Merkle key-value pairs.
   Segment keys C(1)..C(16) are mapped to their component fields.
   Non-segment keys (service accounts C(255,s), etc.) go into extra-kvs.
   Returns: σ closure."
  (let ((segments (make-hash-table))
        (extra '()))
    ;; Classify keyvals
    (dolist (kv keyvals)
      (let* ((key (car kv))
             (val (cdr kv))
             (cn (aref key 0)))
        (if (segment-key-p key)
            (setf (gethash cn segments) val)
            (push (cons key val) extra))))
    ;; Map C(n) → keyword → make-sigma-state argument
    (flet ((seg (cn)
             (gethash cn segments)))
      (make-sigma-state
       :alpha    (seg 1)
       :phi      (seg 2)
       :beta     (seg 3)
       :gamma    (seg 4)
       :psi      (seg 5)
       :eta      (seg 6)
       :iota     (seg 7)
       :kappa    (seg 8)
       :lambda*  (seg 9)
       :rho      (seg 10)
       :tau      (seg 11)
       :chi      (seg 12)
       :pi*      (seg 13)
       :omega    (seg 14)
       :xi       (seg 15)
       :theta    (seg 16)
       :extra-kvs (nreverse extra)))))
