(in-package #:jotl)

(let* ((base (asdf:system-source-directory :jotl))
       (trace-dir (merge-pathnames "../jam-conformance/fuzz-reports/0.7.2/traces/1767871405_1375/" base))
       (step-path (merge-pathnames "00000034.bin" trace-dir)))
  (multiple-value-bind (pre-sigma block-cl post-sigma pre-root post-root)
      (load-trace-step step-path)
    (declare (ignore post-sigma))
    (let* ((e-p (funcall block-cl :preimages))
           (delta (funcall pre-sigma :load :delta)))
      (format t "~&=== TRACE 2 EP ANALYSIS ===~%")
      (format t "EP count: ~D~%" (length e-p))
      (format t "Pre root:  ~A~%" (bytes-to-hex-string pre-root))
      (format t "Post root: ~A~%" (bytes-to-hex-string post-root))
      (format t "Rejected?  ~A~%" (equalp pre-root post-root))
      ;; Show all EP entries with full detail
      (loop for p in e-p for i from 0 do
        (let* ((sid (getf p :requester))
               (blob (ensure-bytes (getf p :blob)))
               (hash (jam.ffi:blake2b-256 blob))
               (len (length blob)))
          (format t "~%  EP[~D]: sid=~D  blob-len=~D~%" i sid len)
          (format t "    hash=~A~%" (bytes-to-hex-string hash))
          (when (> len 0)
            (format t "    blob-first-8=~{~2,'0X ~}~%"
                    (coerce (subseq blob 0 (min 8 len)) 'list)))))
      ;; Check ordering by (sid, blob) tuple - GP eq 12.36
      (format t "~%  === ORDERING CHECK (GP 12.36) ===~%")
      (loop for (p1 p2) on e-p while p2 do
        (let* ((s1 (getf p1 :requester))
               (s2 (getf p2 :requester))
               (b1 (ensure-bytes (getf p1 :blob)))
               (b2 (ensure-bytes (getf p2 :blob))))
          (cond ((< s1 s2)
                 (format t "  (~D,_) < (~D,_) OK (by sid)~%" s1 s2))
                ((= s1 s2)
                 (cond ((equalp b1 b2)
                        (format t "  (~D,blob) = (~D,blob) -> DUPLICATE! REJECT~%" s1 s2))
                       ((bytes< b1 b2)
                        (format t "  (~D,blob1) < (~D,blob2) OK (by blob)~%" s1 s2))
                       (t
                        (format t "  (~D,blob1) > (~D,blob2) -> NOT SORTED! REJECT~%" s1 s2))))
                (t
                 (format t "  (~D,_) > (~D,_) -> NOT SORTED! REJECT~%" s1 s2)))))
      ;; Check Y validation (GP eq 12.22/12.37)
      (format t "~%  === Y VALIDATION CHECK (GP 12.37) ===~%")
      (let ((raw-kvs (funcall delta :raw-kvs)))
        (loop for p in e-p for i from 0 do
          (let* ((sid (getf p :requester))
                 (blob (ensure-bytes (getf p :blob)))
                 (hash (jam.ffi:blake2b-256 blob))
                 (len (length blob))
                 (meta-key (make-service-metadata-key sid))
                 (lookup-key (interleave-sub-key sid (lookup-trie-h hash len))))
            (format t "  EP[~D] sid=~D: " i sid)
            (let ((meta (assoc meta-key raw-kvs :test #'equalp)))
              (unless meta
                (format t "service NOT FOUND -> Y=false, REJECT~%")
                (return))
              (let ((lookup (assoc lookup-key raw-kvs :test #'equalp)))
                (unless lookup
                  (format t "lookup NOT FOUND -> Y=false, REJECT~%")
                  (return))
                (let ((statuses (load-lookup-value (cdr lookup))))
                  (format t "statuses=~A (len=~D) -> Y=~A~%"
                          statuses (length statuses)
                          (cond ((null statuses) "true(GP) true(JOTL)")
                                ((evenp (length statuses)) "false(GP!) true(JOTL!)")
                                (t "false(GP) false(JOTL)")))))))))
      (format t "~%Done.~%"))))
